#!/bin/sh

PROGRAM="$(basename "$0")"
usage() {
    echo "Usage: $(basename "$PROGRAM") [ -l LANG ] [ CODE ]..."
    echo 'Outputs a codeblock in SD_LANG. If no code was'
    echo 'passed as arguments to this command, it will read'
    echo 'the code from stdin.'
    echo ''
    echo '    -l    Specify the language the code is written in.'
    exit "$1"
}

LANG=''
while getopts 'l:h' OPT; do
    case "$OPT" in
        l) LANG="$OPTARG" ;;
        h) usage 0 ;;
        *) usage 1 ;;
    esac
done
shift $((OPTIND-1))

CODE="$*"
code_string() {
    [ -z "$CODE" ] && cat -
    [ -z "$CODE" ] || printf '%s' "$CODE"
}

htmlescape() {
    sed -e 's/&/\&amp;/g' \
        -e 's/</\&lt;/g' \
        -e 's/>/\&gt;/g' \
        -e 's/"/\&quot;/g' \
        -e "s/'/\&#39;/g"
}

[ -z "$SD_LANG" ] && SD_LANG='term'
case "$SD_LANG" in
    html)
        printf '<pre><code'
        [ -z "$LANG" ] || {
            printf ' class="language-'
            printf '%s' "$LANG" | htmlescape
            printf '"'
        }
        printf '>'
        code_string | htmlescape
        echo '</code></pre>'
        ;;
    md)
        # To ensure we always have enough ticks to escape the
        # code, we first count howmany ticks the code contains
        # and the uses that count as the number of ticks in the
        # markdown file"
        CODE_STRING="$(code_string)"
        TICK_COUNT="$(printf '%s```' "$CODE_STRING" | tr -cd '`' | wc -c)"
        TICKS="$(yes '`' | head -n "$TICK_COUNT" | tr -d '\n')"
        echo "$TICKS$LANG"
        printf '%s' "$CODE_STRING" | awk '1'
        echo "$TICKS"
        echo
        ;;
    term)
        code_string | awk '1'
        ;;
esac
