#!/bin/sh

PROGRAM="$(basename "$0")"
usage() {
    echo "Usage: $(basename "$PROGRAM") [ -h ] [ -bci TEXT | TEXT ]..."
    exit "$1"
}

[ "$1" = '-h' ] && usage 0

htmlescape() {
    sed -e 's/&/\&amp;/g' \
        -e 's/</\&lt;/g' \
        -e 's/>/\&gt;/g' \
        -e 's/"/\&quot;/g' \
        -e "s/'/\&#39;/g"
}

[ -z "$SD_LANG" ] && SD_LANG='term'
case "$SD_LANG" in
    html)
        while test "$#" -gt 0; do
            case "$1" in
            -*)
                echo "$1" | grep -o '[bci]' | tr -d '\n' |
                    sed -e 's#b#<strong>#g' \
                        -e 's#c#<code>#g' \
                        -e 's#i#<em>#g'
                printf '%s' "$2" | htmlescape
                echo "$1" | grep -o '[bci]' | tr -d '\n' | rev |
                    sed -e 's#b#</strong>#g' \
                        -e 's#c#</code>#g' \
                        -e 's#i#</em>#g'
                shift 2
                ;;
            *)
                printf '%s' "$1" | htmlescape
                shift 1
                ;;
            esac
        done
        ;;
    md)
        while test "$#" -gt 0; do
            case "$1" in
            -*)
                echo "$1" | grep -o '[bci]' | tr -d '\n' |
                    sed -e 's#b#**#g' \
                        -e 's#c#`#g' \
                        -e 's#i#*#g'
                printf '%s' "$2"
                echo "$1" | grep -o '[bci]' | tr -d '\n' | rev |
                    sed -e 's#b#**#g' \
                        -e 's#c#`#g' \
                        -e 's#i#*#g'
                shift 2
                ;;
            *)
                printf '%s' "$1"
                shift 1
                ;;
            esac
        done
        ;;
    term)
        ESC="$(printf '\x1b')"
        while test "$#" -gt 0; do
            case "$1" in
            -*)
                echo "$1" | grep -o '[bci]' | tr -d '\n' |
                    sed -e "s#b#$ESC[1m#g" \
                        -e "s#c##g" \
                        -e "s#i#$ESC[4m#g"
                printf '%s' "$2"
                echo "$1" | grep -o '[bci]' | tr -d '\n' | rev |
                    sed -e "s#b#$ESC[0m#g" \
                        -e "s#c##g" \
                        -e "s#i#$ESC[0m#g"
                shift 2
                ;;
            *)
                printf '%s' "$1"
                shift 1
                ;;
            esac
        done
        ;;
esac
