#!/bin/sh

PROGRAM="$(basename "$0")"
usage() {
    echo "Usage: $(basename "$PROGRAM") [ -l LEVEL ] [ HEADER ]..."
    echo ''
    echo 'Prints formatted input as a header in SD_LANG.'
    echo 'If no header text is passed as an argument, then'
    echo 'the header is read from stdin.'
    echo 'A header is a container. This means, that it should take'
    echo 'the output of one of the other shelldown commands, and'
    echo 'not text directly, as it will not escape this text'
    echo 'correctly for some output languages.'
    echo ''
    echo 'Do: format "Header" | header'
    echo 'Dont: echo "Header" | header'
    echo ''
    echo '    -l    The level of the header (default 1)'
    exit "$1"
}

LEVEL="1"
while getopts 'l:h' OPT; do
    case "$OPT" in
        l) LEVEL="$OPTARG" ;;
        h) usage 0 ;;
        *) usage 1 ;;
    esac
done
shift $((OPTIND-1))

HEADER="$*"
header_string() {
    [ -z "$HEADER" ] && cat -
    [ -z "$HEADER" ] || printf '%s' "$HEADER"
}


[ -z "$SD_LANG" ] && SD_LANG='term'
case "$SD_LANG" in
    html)
        printf '<h%s>' "$LEVEL"
        header_string
        echo "</h$LEVEL>"
        ;;
    md)
        PREPEND="$(yes '#' | head -n "$LEVEL" | tr -d '\n')"
        header_string | sed "s/^/$PREPEND /" | awk '1'
        echo
        ;;
    term)
        ESC="$(printf '\x1b')"
        header_string | sed -e "s/^/$ESC[1m/" -e "s/\$/$ESC[0m/" | awk '1'
        echo
        ;;
esac
