#!/bin/sh

PROGRAM="$(basename "$0")"
usage() {
    echo "Usage: $(basename "$PROGRAM") [ TEXT ]..."
    echo 'Prints formatted input as a paragraph in SD_LANG.'
    echo 'If no text is passed as an argument, then the text'
    echo 'is read from stdin.'
    echo 'A paragraph is a container. This means, that it should take'
    echo 'the output of one of the other shelldown commands, and'
    echo 'not text directly, as it will not escape this text'
    echo 'correctly for some output languages.'
    echo 'Do: format "Header" | paragraph'
    echo 'Dont: echo "Header" | paragraph'
    exit "$1"
}

while getopts 'h' OPT; do
    case "$OPT" in
        h) usage 0 ;;
        *) usage 1 ;;
    esac
done
shift $((OPTIND-1))

TEXT="$*"
text_string() {
    # Use awk to append missing newline at the endP
    # of our input
    [ -z "$TEXT" ] && cat - | awk '1'
    [ -z "$TEXT" ] || echo "$TEXT"
}


[ -z "$SD_LANG" ] && SD_LANG='term'
case "$SD_LANG" in
    html)
        printf '<p>'
        text_string
        echo '</p>'
        ;;
    md)
        text_string
        echo
        ;;
    term)
        text_string
        echo
        ;;
esac
